owner: empresamais-com-br
repo: status-page-dev

sites:
  - name: Website Dev
    url: https://empresaalvara.com.br
    expectedStatusCodes:
      - 200

status-website:
  baseUrl: /status-page-dev
  name: Status Dev
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
