owner: empresamais-com-br
repo: status-page-dev

workflowSchedule:
  uptime: "* * * * *"

sites:
  - name: Website
    url: https://empresaalvara.com.br
    expectedStatusCodes:
      - 200

status-website:
  baseUrl: /status-page-dev
  name: "Engenharia de Confiabilidade do Sistema"
  logoUrl: https://raw.githubusercontent.com/empresamais-com-br/status-page-dev/master/assets/logo-light.png
  favicon: https://raw.githubusercontent.com/empresamais-com-br/status-page-dev/master/assets/perfil-gmail-500.png
  theme: light
  introTitle: "**Status**"
  introMessage: Acompanhe a disponibilidade dos nossos serviços em tempo real.
  js: |
    // Força formato de data pt-BR
    const originalToLocaleDateString = Date.prototype.toLocaleDateString;
    Date.prototype.toLocaleDateString = function(locale, options) {
      return originalToLocaleDateString.call(this, 'pt-BR', options);
    };
    const originalToLocaleString = Date.prototype.toLocaleString;
    Date.prototype.toLocaleString = function(locale, options) {
      return originalToLocaleString.call(this, 'pt-BR', options);
    };
    const originalToLocaleTimeString = Date.prototype.toLocaleTimeString;
    Date.prototype.toLocaleTimeString = function(locale, options) {
      return originalToLocaleTimeString.call(this, 'pt-BR', options);
    };
  css: |
    @import url('https://fonts.googleapis.com/css2?family=Manrope:wght@400;500;600;700&display=swap');
    
    body, * {
      font-family: 'Manrope', sans-serif !important;
    }
    
    body {
      background: linear-gradient(135deg, #f8f9fa 0%, #ffffff 50%, #f0f2f5 100%) !important;
    }
    
    body::before {
      content: '';
      position: fixed;
      top: 0;
      left: 0;
      right: 0;
      bottom: 0;
      background-image: 
        linear-gradient(rgba(0, 212, 255, 0.03) 1px, transparent 1px),
        linear-gradient(90deg, rgba(0, 212, 255, 0.03) 1px, transparent 1px);
      background-size: 40px 40px;
      pointer-events: none;
      z-index: 0;
    }
    
    a {
      color: #00d4ff !important;
    }
    
    a:hover {
      color: #00ffcc !important;
    }
    
    nav {
      background: rgba(255, 255, 255, 0.95) !important;
      border-bottom: 1px solid rgba(0, 212, 255, 0.2) !important;
      backdrop-filter: blur(10px);
    }
    
    footer {
      border-top: 1px solid rgba(0, 0, 0, 0.1) !important;
    }

i18n:
  # ========================================
  # PÁGINA PRINCIPAL
  # ========================================
  activeIncidents: "Incidentes Ativos"
  allSystemsOperational: "Todos os sistemas operacionais"
  
  # ========================================
  # STATUS EM TEMPO REAL
  # ========================================
  liveStatus: "Status em Tempo Real"
  overallUptime: "Disponibilidade geral: $UPTIME"
  overallUptimeTitle: "Disponibilidade geral"
  
  # ========================================
  # PÁGINA DE DETALHES DO SITE
  # ========================================
  sevelDayResponseTime: "Tempo de resposta de 7 dias"
  averageResponseTime: "Tempo médio de resposta: $TIMEms"
  averageResponseTimeTitle: "Tempo médio de resposta"
  responseTimeMs: "Tempo de resposta (ms)"
  weightedAverage: "Média ponderada"
  
  # ========================================
  # INCIDENTES - LISTAGEM
  # ========================================
  incidentReport: "Relatório do incidente #$NUMBER →"
  activeIncidentSummary: "Aberto em $DATE com $POSTS atualizações"
  pastIncidents: "Incidentes Anteriores"
  pastIncidentsResolved: "Resolvido em $MINUTES minutos com $POSTS atualizações"
  
  # ========================================
  # INCIDENTES - DETALHES
  # ========================================
  incidentTitle: "Detalhes do incidente $NUMBER"
  incidentDetails: "Detalhes do incidente"
  incidentFixed: "Resolvido"
  incidentOngoing: "Em andamento"
  incidentOpenedAt: "Aberto em"
  incidentClosedAt: "Fechado em"
  incidentSubscribe: "Inscrever-se para atualizações"
  incidentViewOnGitHub: "Ver no GitHub"
  incidentCommentSummary: "Publicado em $DATE por $AUTHOR"
  incidentBack: "← Voltar aos incidentes"
  
  # ========================================
  # STATUS DOS INCIDENTES
  # ========================================
  ongoing: "Em andamento"
  resolved: "Resolvido"
  identified: "Identificado"
  investigating: "Investigando"
  monitoring: "Monitorando"
  
  # ========================================
  # NAVEGAÇÃO
  # ========================================
  backToAllIncidents: "← Voltar para todos os incidentes"
  viewAndSubscribe: "Ver e Inscrever-se no GitHub"
  navGitHub: "GitHub"
  
  # ========================================
  # MANUTENÇÃO PROGRAMADA
  # ========================================
  scheduledMaintenance: "Manutenção Programada"
  scheduledMaintenanceDetails: "Programado para $DATE às $TIME"
  startedAt: "Iniciado em"
  
  # ========================================
  # ESTADOS
  # ========================================
  up: "Operacional"
  down: "Fora do ar"
  degraded: "Degradado"
  unknown: "Desconhecido"
  loading: "Carregando..."
  
  # ========================================
  # MÉTRICAS
  # ========================================
  responseTime: "Tempo de resposta"
  uptime: "Disponibilidade"
  uptimePercent: "$UPTIME%"
  
  # ========================================
  # TEMPO
  # ========================================
  day: "dia"
  days: "dias"
  hour: "hora"
  hours: "horas"
  minute: "minuto"
  minutes: "minutos"
  second: "segundo"
  seconds: "segundos"
  ms: "ms"
  
  # ========================================
  # DATA E HORA
  # ========================================
  dateAndTime: "$DATE às $TIME"
  
  # ========================================
  # PERÍODOS DE TEMPO
  # ========================================
  time24h: "24h"
  time7d: "7d"
  time30d: "30d"
  time1y: "1a"
  timeAll: "tudo"
  
  # ========================================
  # TABELA
  # ========================================
  status: "Status"
  history: "Histórico"
  url: "URL"
  
  # ========================================
  # RODAPÉ
  # ========================================
  footer: "© EmpresaMais™"
  
  # ========================================
  # ERRO DE RATE LIMIT (API do GitHub)
  # ========================================
  rateLimitExceededTitle: "Limite de requisições excedido"
  rateLimitExceededIntro: "Você excedeu o número de requisições que pode fazer em uma hora, então precisará esperar antes de acessar este site novamente. Alternativamente, você pode adicionar um Token de Acesso Pessoal do GitHub para continuar usando este site."
  rateLimitExceededWhatDoesErrorMean: "O que significa este erro?"
  rateLimitExceededErrorMeaning: "Este site usa a API do GitHub para acessar dados em tempo real sobre o status dos nossos serviços. Por padrão, o GitHub permite 60 requisições por hora por endereço IP, que você consumiu."
  rateLimitExceededErrorHowCanFix: "Como posso resolver?"
  rateLimitExceededErrorFix: "Você pode esperar mais uma hora e o limite do seu endereço IP será restaurado. Alternativamente, você pode adicionar seu Token de Acesso Pessoal do GitHub, que te dá 5.000 requisições adicionais por hora."
  rateLimitExceededGeneratePAT: "Aprenda como gerar um Token de Acesso Pessoal"
  rateLimitExceededHasSet: "Você tem um token de acesso pessoal configurado."
  
  # ========================================
  # ERROS GERAIS
  # ========================================
  errorIntro: "Ops! Ocorreu um erro ao tentar carregar os status de disponibilidade."
  errorText: "Por favor, tente novamente em alguns instantes."