owner: empresamais-com-br
repo: status-page-dev

workflowSchedule:
  uptime: "* * * * *"

sites:
  - name: Website Dev
    url: https://empresaalvara.com.br
    expectedStatusCodes:
      - 200

status-website:
  baseUrl: /status-page-dev
  name: ""
  logoUrl: https://raw.githubusercontent.com/empresamais-com-br/status-page-dev/master/assets/logo-white.png
  theme: dark
  introTitle: "**Status do Sistema**"
  introMessage: Acompanhe a disponibilidade dos nossos serviços em tempo real.
  customCss: assets/custom.css
  navbar:
    - title: Status
      href: /
    - title: Site
      href: https://empresaalvara.com.br