owner: empresamais-com-br
repo: status-page-dev

workflowSchedule:
  uptime: "* * * * *"

sites:
  - name: Website Dev
    url: https://empresaalvara.com.br
    expectedStatusCodes:
      - 200

status-website:
  baseUrl: /status-page-dev
  name: "Engenharia de Confiabilidade do Sistema"
  logoUrl: https://raw.githubusercontent.com/empresamais-com-br/status-page-dev/master/assets/logo-light.png
  favicon: https://raw.githubusercontent.com/empresamais-com-br/status-page-dev/master/assets/perfil-gmail-500.png
  theme: light
  introTitle: "**Status**"
  introMessage: Acompanhe a disponibilidade dos nossos serviços em tempo real.
  js: |
    // Força formato de data pt-BR
    const originalToLocaleDateString = Date.prototype.toLocaleDateString;
    Date.prototype.toLocaleDateString = function(locale, options) {
      return originalToLocaleDateString.call(this, 'pt-BR', options);
    };
    const originalToLocaleString = Date.prototype.toLocaleString;
    Date.prototype.toLocaleString = function(locale, options) {
      return originalToLocaleString.call(this, 'pt-BR', options);
    };
    const originalToLocaleTimeString = Date.prototype.toLocaleTimeString;
    Date.prototype.toLocaleTimeString = function(locale, options) {
      return originalToLocaleTimeString.call(this, 'pt-BR', options);
    };
  css: |
    @import url('https://fonts.googleapis.com/css2?family=Manrope:wght@400;500;600;700&display=swap');
    
    body, * {
      font-family: 'Manrope', sans-serif !important;
    }
    
    body {
      background: linear-gradient(135deg, #f8f9fa 0%, #ffffff 50%, #f0f2f5 100%) !important;
    }
    
    body::before {
      content: '';
      position: fixed;
      top: 0;
      left: 0;
      right: 0;
      bottom: 0;
      background-image: 
        linear-gradient(rgba(0, 212, 255, 0.03) 1px, transparent 1px),
        linear-gradient(90deg, rgba(0, 212, 255, 0.03) 1px, transparent 1px);
      background-size: 40px 40px;
      pointer-events: none;
      z-index: 0;
    }
    
    a {
      color: #00d4ff !important;
    }
    
    a:hover {
      color: #00ffcc !important;
    }
    
    nav {
      background: rgba(255, 255, 255, 0.95) !important;
      border-bottom: 1px solid rgba(0, 212, 255, 0.2) !important;
      backdrop-filter: blur(10px);
    }
    
    footer {
      border-top: 1px solid rgba(0, 0, 0, 0.1) !important;
    }

i18n:
  footer: "© EmpresaMais™"
  activeIncidents: "Incidentes Ativos"
  allSystemsOperational: "Todos os sistemas operacionais"
  incidentReport: "Relatório do incidente"
  weightedAverage: "Média ponderada"
  averageResponseTime: "Tempo médio de resposta"
  liveStatus: "Status em Tempo Real"
  overallUptime: "Disponibilidade geral"
  overallUptimeXdays: "Disponibilidade geral (últimos $DAYS dias)"
  day: "dia"
  days: "dias"
  hour: "hora"
  hours: "horas"
  minute: "minuto"
  minutes: "minutos"
  second: "segundo"
  seconds: "segundos"
  ms: "ms"
  loading: "Carregando..."
  up: "Operacional"
  down: "Fora do ar"
  degraded: "Degradado"
  unknown: "Desconhecido"
  dateAndTime: "$DATE às $TIME"
  incidentTitle: "$SITE está $STATUS"
  incidentDetails: "Aberto em $DATE às $TIME com $POSTS atualizações"
  pastIncidents: "Incidentes Anteriores"
  pastIncidentsResolved: "Resolvido em $MINUTES minutos"
  scheduledMaintenance: "Manutenção Programada"
  scheduledMaintenanceDetails: "Programado para $DATE às $TIME"
  startedAt: "Iniciado em"
  responseTime: "Tempo de resposta"
  responseTimeMs: "$TIME ms"
  uptime: "Disponibilidade"
  uptimePercent: "$UPTIME%"
  status: "Status"
  history: "Histórico"
  url: "URL"
  time24h: "24h"
  time7d: "7d"
  time30d: "30d"
  time1y: "1a"
  timeAll: "tudo"