owner: empresamais-com-br
repo: status-page-dev

sites:
  - name: Website Dev
    url: https://empresaalvara.com.br
    expectedStatusCodes:
      - 200

status-website:
  baseUrl: /status-page-dev
  # name: EmpresaAlvara Status
  name: ""
  logoUrl: https://raw.githubusercontent.com/empresamais-com-br/status-page-dev/master/assets/logo.png  
  theme: light
  
  # Textos customizados
  introTitle: "**Status do Sistema**"
  introMessage: Acompanhe a disponibilidade dos nossos serviços em tempo real.
  
  # Navbar
  navbar:
    - title: Status
      href: /
    - title: Site
      href: https://empresaalvara.com.br

# Cores customizadas (CSS)
customCSS: |
  :root {
    --color-primary: #2563eb;
    --color-success: #22c55e;
    --color-danger: #ef4444;
  }